Query 1
"Select card_holder.cardholder_id, card_holder.name, transaction_activity.amount, merchant_category.name as MerchantCategory, transaction_activity.date,  credit_card.card, merchant.name as MerchantName from transaction_activity   left JOIN merchant  on transaction_activity.merchant_id = merchant.merchant_id left JOIN merchant_category on merchant.merchant_category_id = merchant_category.merchant_category_id left join credit_card on transaction_activity.card =  credit_card.card left join card_holder on credit_card.cardholder_id = card_holder.cardholder_id  where card_holder.cardholder_id in (2,18) order by card_holder, date, amount asc" 

Query 2
"Select card_holder.cardholder_id, card_holder.name, transaction_activity.amount, merchant_category.name as MerchantCategory, transaction_activity.date,  credit_card.card, merchant.name as MerchantName from transaction_activity   left JOIN merchant  on transaction_activity.merchant_id = merchant.merchant_id left JOIN merchant_category on merchant.merchant_category_id = merchant_category.merchant_category_id left join credit_card on transaction_activity.card =  credit_card.card left join card_holder on credit_card.cardholder_id = card_holder.cardholder_id  where card_holder.cardholder_id in (2) order by card_holder, date, amount asc" 

Query 3
"Select card_holder.cardholder_id, card_holder.name, transaction_activity.amount, merchant_category.name as MerchantCategory, transaction_activity.date,  credit_card.card, merchant.name as MerchantName from transaction_activity   left JOIN merchant  on transaction_activity.merchant_id = merchant.merchant_id left JOIN merchant_category on merchant.merchant_category_id = merchant_category.merchant_category_id left join credit_card on transaction_activity.card =  credit_card.card left join card_holder on credit_card.cardholder_id = card_holder.cardholder_id  where card_holder.cardholder_id in (18) order by card_holder, date, amount asc" 

Query 4
"Select  card_holder.cardholder_id, card_holder.name, transaction_activity.amount, merchant_category.name as MerchantCategory, transaction_activity.date, credit_card.card, merchant.name as MerchantName from transaction_activity left JOIN merchant on transaction_activity.merchant_id = merchant.merchant_id	left JOIN merchant_category on merchant.merchant_category_id = merchant_category.merchant_category_id	left join credit_card	on transaction_activity.card =  credit_card.card	left join card_holder	on credit_card.cardholder_id = card_holder.cardholder_id where card_holder.cardholder_id in (25) and transaction_activity.date > '2017-12-31' and transaction_activity.date < '2018-07-01' order by date, amount asc"

Query 5 
"Select  TO_CHAR(transaction_activity.date, 'Month') as month , EXTRACT(DAY from transaction_activity.date) as day , transaction_activity.amount from transaction_activity left JOIN merchant on transaction_activity.merchant_id = merchant.merchant_id left JOIN merchant_category on merchant.merchant_category_id = merchant_category.merchant_category_id left join credit_card on transaction_activity.card =  credit_card.card left join card_holder on credit_card.cardholder_id = card_holder.cardholder_id  where card_holder.cardholder_id in (25)and transaction_activity.date > '2017-12-31'and transaction_activity.date < '2018-07-01' order by date, amount asc"